### PR TITLE
SINGA-67 Add singatest into build targets

### PR DESCRIPTION
**Pull request by xiezl**
Modified Makefile.am to add a target named "singatest".
Now "make" will generate 5 files/libs: libsinga.la libgtest.la singa singatool singatest.
User can also specify the target he wants to generate, for example, "make singa".

### CODE REVIEW

**Comment by nudles** [comment]
could you separate the test part with the core part?

particularly, we provided three compiling commands,

    make

compiles the core part.

    make test

compiles the test part.

    make all

compiles both.

Would it be better?
Thank you.

**Comment by xiezl** [comment]
updated with your comments and SINGA-69.

**Comment by nudles** [comment]
the compilation generates many screen outputs...
it would be better to hide these screen outputs like the previous version.

rename `enable-singatest` to `enable-test`?

**Comment by xiezl** [comment]
All updated.

**Comment by nudles** [comment]
summary:

1.  compile with `-g`
     
       ./configure --enable-debug
        make

2. compile both singa core and test code
  
        ./configure --enable-test
        make

    or

        ./configure 
        make  // compile core only
        make singatest   // compile test only

**Pull request merged**
