### PR TITLE
SINGA-387 Modified the design of autograd backward engine and correct some mistakes in it

### PR DESCRIPTION
**Pull request by xuewanqi**

### CODE REVIEW

**Comment by nudles** [comment]
can you rebase the PR and add the jira ticket number in the commit msg?

**Comment by xuewanqi** [comment]
ok.noted

**Comment by xuewanqi** [comment]
I didn't run the unit tests. i run example networks in folder example/autograd. 

I just read the related code, maybe caused by mumber function of tensor, reshape().

**Comment by xuewanqi** [comment]
need to change from x.reshape(.) to x=x.reshape(.)

**Pull request merged**
