### PR TITLE
SINGA-139 Fixed a bug in built-in convolution layer

### PR DESCRIPTION
**Pull request by XiangruiCAI**
For convolution.cc, change the order of parameters for Im2col and Col2im functions.

### CODE REVIEW

**Comment by nudles** [comment]
xiangrui, pls follow this guide  http://singa.apache.org/develop/contribute-code.html to contribute code to SINGA. Thanks.

**Comment by XiangruiCAI** [comment]
OK, thanks. I'll do it.

Best regards!
Xiangrui

**Comment by nudles** [comment]
have you updated the commit msg title?

**Comment by nudles** [comment]
Pls close this pull request as it is resolved in #126

**Pull request closed without merging**
